### ISSUE TITLE
Meta files - Inconsistent guids

### ISSUE THREAD

**Issue by zaucy** [MCpiroman/UnityNativeTool#16]
Hey, first of all I would like to say thanks for creating this project!

I have a project where we fetch our third party dependencies (including UnityNativeTool) instead of having them checked in to our source control. In our other third party dependencies they include the .meta files. I see in UnityNativeTool the .meta files are not checked into GitHub. This results in different guids being generated on different machines with our setup. To get around this I made a fork and just committed the meta files (https://github.com/zaucy/UnityNativeTool/tree/with-meta-files).

It's a non-issue for me to maintain the fork for my project. I was just wondering if it may be ideal to include the .meta files incase someone else runs into the same issue :)

**Comment by mcpiroman** [comment]
cc @rogerbarton, isn't that something that that your recent upm support PR would solve? I've read you mentioned meta files there. If so, it would be quite a miracle that a problem and it's solution appeared in the same day, completely independently, in a project of this scale :).

I generally haven't realized such need existed, albeit I know that in other management solutions (like npm, nuget) things like guids and hashes are indeed a thing. I'm not really into Unity ATM :). I guess I'll look at other Unity related repos and try to fit the standard.

(I'm also assuming you're using this repo directly instead of .unitypackage, right? From my knowledge Unity should append meta files there.)

Anyway, thanks for suggestion.

**Comment by rogerbarton** [comment]
Yes this is what I mentioned in #14. However, this is unrelated to upm and we can just change the `.gitignore`. I will change it in that PR.

That's indeed quite good timing :)

**Comment by zaucy** [comment]
Yeah at the moment we're not using the .unitypackage. That is something I could look at using as an alternative. I'm not too familiar with them though so I'd have to see how I could integrate it with our third party dependency management.

**Comment by mcpiroman** [comment]
Closed by #14
